{% set name = "suby" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/suby-{{ version }}.tar.gz
  sha256: a8a8f8da689b2a3f854c9048a299510d853eec6572ac4ffd7799c9a7f59aaa13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7
    - emptylog >=0.0.3
    - cantok >=0.0.18

test:
  imports:
    - suby
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/suby
  summary: Slightly simplified subprocesses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
