schema_version: 1

context:
  name: suby
  version: "0.0.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/suby-${{ version }}.tar.gz
  sha256: 1c9c6f5bbf3102b750669fb02549fac27b6665c282e5b030b69d34d99f21442a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - emptylog >=0.0.12
    - cantok >=0.0.36

tests:
  - python:
      imports:
        - suby
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Slightly simplified subprocesses
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pomponchik/suby

extra:
  recipe-maintainers:
    - thewchan
