schema_version: 1

context:
  name: suby
  version: "0.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/suby-${{ version }}.tar.gz
  sha256: fdd94581b0f7169ba6451cb163dfff96bd5e83011c4f30b7335dc61e15a8d1b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - emptylog >=0.0.12
    - cantok >=0.0.36

tests:
  - python:
      imports:
        - suby
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Slightly simplified subprocesses
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pomponchik/suby

extra:
  recipe-maintainers:
    - thewchan
